import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import SEO from '../components/SEO';

export default function Disclaimer() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
      <SEO 
        title="Disclaimer - LoveyouTools" 
        description="Read our medical, legal, and general tools disclaimer for using LoveyouTools website."
        url={window.location.href}
      />
      
      <Link to="/" className="inline-flex items-center gap-2 text-text-muted hover:text-accent mb-8 transition-colors">
        <ArrowLeft className="w-4 h-4" /> Back to Home
      </Link>

      <h1 className="text-4xl font-extrabold mb-8">Disclaimer</h1>
      <div className="prose prose-lg dark:prose-invert max-w-none space-y-6 text-text-secondary">
        <p className="text-sm text-text-muted italic">Last Updated: April 19, 2026</p>

        <h2 className="text-2xl font-bold text-text-primary mt-12 mb-4">1. General Information</h2>
        <p>
          All the information on this website - https://loveyoutools.in/ - is published in good faith and for general information and utility purposes only. LoveyouTools does not make any warranties about the completeness, reliability, and accuracy of this information or the output generated by our tools.
        </p>

        <h2 className="text-2xl font-bold text-text-primary mt-12 mb-4">2. Tool Usage and Accuracy</h2>
        <p>
          Any action you take upon the information you find on this website or the outputs you generate using our tools (such as document conversions, image processing, calculations, or textual formatting) is strictly at your own risk. LoveyouTools will not be liable for any losses and/or damages in connection with the use of our website or tools.
        </p>

        <h2 className="text-2xl font-bold text-text-primary mt-12 mb-4">3. Local Processing</h2>
        <p>
          While we strive to ensure 100% local, client-side processing for majority of our tools to protect your privacy, you are solely responsible for ensuring you do not process highly sensitive, confidential, or legally binding material without verifying the tool's absolute necessity.
        </p>

        <h2 className="text-2xl font-bold text-text-primary mt-12 mb-4">4. External Links</h2>
        <p>
          From our website, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites.
        </p>

        <h2 className="text-2xl font-bold text-text-primary mt-12 mb-4">5. AdSense Policy Compliance</h2>
        <p>
          This website may feature advertisements sourced from third-party networks, including Google AdSense. We do not endorse the products or services advertised therein. Google uses cookies to serve ads based on your prior visits to our website or other websites. Please refer to our Privacy Policy for more details on advertising cookies.
        </p>

        <h2 className="text-2xl font-bold text-text-primary mt-12 mb-4">6. Consent</h2>
        <p>
          By using our website, you hereby consent to our disclaimer and agree to its terms.
        </p>
      </div>
    </div>
  );
}
